import { Box } from "@mui/material";
import Head from "next/head";
import { CardPurchaseSection } from "../components/CardPurchaseSection";
import { HomeHeroSection } from "../components/HomeHeroSection";
import { HomeWhySection } from "../components/HomeWhySection";
import { ImageGallary } from "../components/ImageGallary";
import { WhyChooseMe } from "../components/WhyChooseMe";

export default function Home() {
  return (
    <Box bgcolor={"background"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeroSection />
      <WhyChooseMe />
      <CardPurchaseSection />
      <HomeWhySection />
      <ImageGallary />
    </Box>
  );
}
